/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package momentFrames;
import frams.HomePage;
import frams.MainFrame;
import frams.PremiumHome;
import moment.Memory;
import user.PremiumUser;
import user.User;
import usersData.UsersData;
/**
 *
 * @author PC
 */
public class DisplayMemory extends MainFrame {
    
    Memory memory;
    int userIndex;
    
    public DisplayMemory(Memory m , int userIndex) {
         initComponents();
         memory=m;
        display();
       this.userIndex = userIndex;
        this.setSize(630, 1090);
    }
public void display()
{
     name.setText(memory.getMomentName());
      location.setText(memory.getLocation());
       hPoints.setText(String.valueOf(memory.getHappinessPoints()));
       sPoints.setText(String.valueOf(memory.getSadnessPoints()));
       year.setText(String.valueOf(memory.getActualYear()));
       rate.setText(String.valueOf(memory.getImportanceRate()));
       description.setText(String.valueOf(memory.getDescription()));
       CalcHappTF.setText(String.valueOf(memory.CalculateHappiness()));
       CalcHappTF.setEditable(false);

}
   

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        location = new javax.swing.JTextField();
        hPoints = new javax.swing.JTextField();
        rate = new javax.swing.JTextField();
        sPoints = new javax.swing.JTextField();
        year = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        description = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        calcHapp = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CalcHappTF = new javax.swing.JTextField();
        back = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Segoe Script", 3, 30)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Your Memories");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 100, 280, 40);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 51));
        jLabel3.setText("Memory name");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(80, 210, 110, 20);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(153, 0, 51));
        jLabel4.setText("Importance Rate");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(90, 480, 130, 20);

        jLabel5.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(153, 0, 51));
        jLabel5.setText("Location");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(90, 280, 70, 20);

        jLabel6.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 0, 51));
        jLabel6.setText("Happiness Points");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(90, 350, 140, 20);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 17)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(153, 0, 51));
        jLabel7.setText("Sadness Points");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(90, 410, 140, 21);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 17)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(153, 0, 51));
        jLabel8.setText("Actual year");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(90, 600, 100, 20);

        jLabel9.setFont(new java.awt.Font("Arial", 3, 17)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(153, 0, 51));
        jLabel9.setText("Description");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(90, 660, 100, 20);

        name.setEditable(false);
        name.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(name);
        name.setBounds(240, 210, 210, 40);

        location.setEditable(false);
        location.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(location);
        location.setBounds(240, 280, 210, 40);

        hPoints.setEditable(false);
        hPoints.setBackground(new java.awt.Color(255, 255, 255));
        hPoints.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(hPoints);
        hPoints.setBounds(240, 350, 50, 40);

        rate.setEditable(false);
        rate.setBackground(new java.awt.Color(255, 255, 255));
        rate.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(rate);
        rate.setBounds(240, 480, 50, 40);

        sPoints.setEditable(false);
        sPoints.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(sPoints);
        sPoints.setBounds(240, 410, 50, 40);

        year.setEditable(false);
        year.setBackground(new java.awt.Color(255, 255, 255));
        year.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(year);
        year.setBounds(240, 590, 100, 40);

        description.setEditable(false);
        description.setColumns(22);
        description.setFont(new java.awt.Font("Courier New", 0, 16)); // NOI18N
        description.setLineWrap(true);
        description.setRows(25);
        jScrollPane1.setViewportView(description);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(230, 650, 280, 230);

        jButton1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 102, 102));
        jButton1.setText("<-  BackHome");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 920, 130, 40);
        jPanel1.add(calcHapp);
        calcHapp.setBounds(0, 0, 0, 950);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(102, 0, 0));
        jLabel10.setText("Calc Happiness");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(90, 530, 120, 30);

        CalcHappTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcHappTFActionPerformed(evt);
            }
        });
        jPanel1.add(CalcHappTF);
        CalcHappTF.setBounds(240, 540, 50, 40);

        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/homeFram/Welpaper.jpg"))); // NOI18N
        jPanel1.add(back);
        back.setBounds(0, 0, 690, 1050);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 681, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 991, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        this.setVisible(false);
           if (users[userIndex] instanceof PremiumUser)
            {
                new PremiumHome(userIndex).setVisible(true);
            }
            else
            {
                new HomePage(userIndex).setVisible(true);
            }
                                         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CalcHappTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcHappTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcHappTFActionPerformed

      private final UsersData usersData = UsersData.getUsersData();
        private final User [] users = usersData.getUsers();

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CalcHappTF;
    private javax.swing.JLabel back;
    private javax.swing.JLabel calcHapp;
    private javax.swing.JTextField calcHappinesTF;
    private javax.swing.JTextArea description;
    private javax.swing.JTextField hPoints;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField location;
    private javax.swing.JTextField name;
    private javax.swing.JTextField rate;
    private javax.swing.JTextField sPoints;
    private javax.swing.JTextField year;
    // End of variables declaration//GEN-END:variables
}
